### ISSUE TITLE
a change and a question

### ISSUE THREAD

**Issue by obedm503** [develephant/Amy#2]
First of the "ipc" module is deprecated and should be changed to ("electron").ipcMain

Also, when trying to run the app with electron, an error comes up saying that the app provided is not a valid Electron app, and points me to the docs then it says Error: Cannont find module './client/lib/ng-electon/ng-bridge'

**Comment by obedm503** [comment]
solved it by doing bower install on the client folder

**Comment by develephant** [comment]
Hi,

Yes indeed some items need to be updated to reach parity with the current version of Electron. Will be updating shortly. Thanks for reporting.
